#!/bin/sh
set -eu
docker compose version
for compose_file in compose.yaml deploy/bundle/compose.yaml; do
  rendered="$(BUCKETREEF_TAG=0.0.0 INTERNAL_CRON_TOKEN=test docker compose --file "$compose_file" config --format json)"
  test "$(printf '%s' "$rendered" | jq -r '.services.frontend.environment.CSP_CONNECT_SRC')" = "'self'"
  printf '%s' "$rendered" | jq -e '.services.backend.healthcheck.test and .services.frontend.healthcheck.test' >/dev/null
  printf '%s' "$rendered" | jq -e '.services.backend.read_only and .services.frontend.read_only and .services.scheduler.read_only' >/dev/null
  test "$(printf '%s' "$rendered" | jq -r '.services.frontend.ports[0].target')" = "8080"
  test "$(printf '%s' "$rendered" | jq -r '.services.scheduler.user')" = "10001:10001"
  test "$(printf '%s' "$rendered" | jq -r '.services.scheduler.profiles // empty')" = ""
  test "$(printf '%s' "$rendered" | jq -r '.services.backend.environment.DEPLOYMENT_PROFILE')" = "full"

  compose_dir="$(dirname "$compose_file")"
  admin_override="$compose_dir/compose.admin.yaml"
  admin_no_ceph_override="$compose_dir/compose.admin-no-ceph-admin.yaml"
  user_override="$compose_dir/compose.user.yaml"
  ceph_admin_override="$compose_dir/compose.ceph-admin-high-security.yaml"
  rendered_admin="$(BUCKETREEF_TAG=0.0.0 INTERNAL_CRON_TOKEN=test docker compose --file "$compose_file" --file "$admin_override" config --format json)"
  rendered_admin_no_ceph="$(BUCKETREEF_TAG=0.0.0 INTERNAL_CRON_TOKEN=test docker compose --file "$compose_file" --file "$admin_no_ceph_override" config --format json)"
  rendered_user="$(BUCKETREEF_TAG=0.0.0 INTERNAL_CRON_TOKEN=test docker compose --file "$compose_file" --file "$user_override" config --format json)"
  rendered_ceph_admin="$(BUCKETREEF_TAG=0.0.0 docker compose --file "$compose_file" --file "$ceph_admin_override" config --format json)"
  test "$(printf '%s' "$rendered_admin" | jq -r '.services.backend.environment.FEATURE_ADMIN_ENABLED')" = "true"
  test "$(printf '%s' "$rendered_admin" | jq -r '.services.backend.environment.DEPLOYMENT_PROFILE')" = "admin"
  test "$(printf '%s' "$rendered_admin" | jq -r '.services.backend.environment.FEATURE_CEPH_ADMIN_ENABLED')" = "true"
  test "$(printf '%s' "$rendered_admin" | jq -r '.services.backend.environment.FEATURE_MANAGER_ENABLED')" = "false"
  test "$(printf '%s' "$rendered_admin" | jq -r '.services.backend.environment.SCHEDULED_JOBS_ENABLED')" = "true"
  test "$(printf '%s' "$rendered_admin" | jq -r '.services.backend.environment.WEBHOOK_WORKER_ENABLED')" = "true"
  test "$(printf '%s' "$rendered_admin_no_ceph" | jq -r '.services.backend.environment.DEPLOYMENT_PROFILE')" = "admin-no-ceph-admin"
  test "$(printf '%s' "$rendered_admin_no_ceph" | jq -r '.services.backend.environment.FEATURE_ADMIN_ENABLED')" = "true"
  test "$(printf '%s' "$rendered_admin_no_ceph" | jq -r '.services.backend.environment.FEATURE_CEPH_ADMIN_ENABLED')" = "false"
  test "$(printf '%s' "$rendered_admin_no_ceph" | jq -r '.services.backend.environment.FEATURE_STORAGE_OPS_ENABLED')" = "true"
  test "$(printf '%s' "$rendered_admin_no_ceph" | jq -r '.services.backend.environment.SCHEDULED_JOBS_ENABLED')" = "true"
  test "$(printf '%s' "$rendered_admin_no_ceph" | jq -r '.services.backend.environment.WEBHOOK_WORKER_ENABLED')" = "true"
  test "$(printf '%s' "$rendered_user" | jq -r '.services.backend.environment.FEATURE_ADMIN_ENABLED')" = "false"
  test "$(printf '%s' "$rendered_user" | jq -r '.services.backend.environment.DEPLOYMENT_PROFILE')" = "user"
  test "$(printf '%s' "$rendered_user" | jq -r '.services.backend.environment.FEATURE_MANAGER_ENABLED')" = "true"
  test "$(printf '%s' "$rendered_user" | jq -r '.services.backend.environment.SCHEDULED_JOBS_ENABLED')" = "false"
  test "$(printf '%s' "$rendered_user" | jq -r '.services.backend.environment.WEBHOOK_WORKER_ENABLED')" = "false"
  test "$(printf '%s' "$rendered_ceph_admin" | jq -r '.services.backend.environment.CEPH_ADMIN_HIGH_SECURITY_MODE')" = "true"
  test "$(printf '%s' "$rendered_ceph_admin" | jq -r '.services.backend.environment.DEPLOYMENT_PROFILE')" = "ceph-admin-high-security"
  test "$(printf '%s' "$rendered_ceph_admin" | jq -r '.services.backend.environment.FEATURE_ADMIN_ENABLED')" = "false"
  test "$(printf '%s' "$rendered_ceph_admin" | jq -r '.services.backend.environment.FEATURE_CEPH_ADMIN_ENABLED')" = "true"
  test "$(printf '%s' "$rendered_ceph_admin" | jq -r '.services.backend.environment.FEATURE_MANAGER_ENABLED')" = "false"
  test "$(printf '%s' "$rendered_ceph_admin" | jq -r '.services.backend.environment.SCHEDULED_JOBS_ENABLED')" = "false"
  test "$(printf '%s' "$rendered_ceph_admin" | jq -r '.services.backend.environment.WEBHOOK_WORKER_ENABLED')" = "false"
done
