/* Copyright (c) 2026 Laurent Barbe. Licensed under the Apache License, Version 2.0. */
const l = (en: string, fr: string, de: string, zh: string) => ({ en, fr, de, zh });

export const onboardingCopy = {
  title: l("Getting started", "Bien démarrer", "Erste Schritte", "入门"),
  description: l(
    "Connect your S3 storage, then choose what BucketReef should prepare for you.",
    "Connectez votre stockage S3, puis choisissez ce que BucketReef doit préparer pour vous.",
    "Verbinden Sie Ihren S3-Speicher und wählen Sie anschließend aus, was BucketReef vorbereiten soll.",
    "连接您的 S3 存储，然后选择由 BucketReef 为您准备的功能。",
  ),
  optional: l(
    "This assistant only enables the features and access you select. You can configure everything in more detail later.",
    "Cet assistant active uniquement les fonctionnalités et les accès que vous sélectionnez. Vous pourrez tout affiner ensuite.",
    "Dieser Assistent aktiviert nur die ausgewählten Funktionen und Zugriffe. Details können später angepasst werden.",
    "此向导只会启用您选择的功能和权限，之后仍可进行更细致的配置。",
  ),
  connectStep: l("1. Connect storage", "1. Connecter le stockage", "1. Speicher verbinden", "1. 连接存储"),
  prepareStep: l("2. Prepare BucketReef", "2. Préparer BucketReef", "2. BucketReef vorbereiten", "2. 准备 BucketReef"),
  endpointTitle: l("Storage endpoint", "Endpoint de stockage", "Speicher-Endpunkt", "存储端点"),
  endpointHelp: l(
    "Reuse an endpoint already configured by an administrator, or add a Ceph RGW endpoint.",
    "Réutilisez un endpoint déjà configuré par un administrateur, ou ajoutez un endpoint Ceph RGW.",
    "Verwenden Sie einen bereits eingerichteten Endpunkt oder fügen Sie einen Ceph-RGW-Endpunkt hinzu.",
    "复用管理员已配置的端点，或添加 Ceph RGW 端点。",
  ),
  endpointChoice: l("Endpoint", "Endpoint", "Endpunkt", "端点"),
  newEndpoint: l("Add a new Ceph RGW endpoint", "Ajouter un endpoint Ceph RGW", "Neuen Ceph-RGW-Endpunkt hinzufügen", "添加新的 Ceph RGW 端点"),
  endpointUrl: l("S3 endpoint URL", "URL de l’endpoint S3", "S3-Endpunkt-URL", "S3 端点 URL"),
  adminCredentials: l("Ceph administration credentials", "Clés d’administration Ceph", "Ceph-Administrationszugang", "Ceph 管理凭据"),
  adminCredentialsHelp: l(
    "Recommended. BucketReef uses these keys to detect RGW Account and Ceph Admin capabilities. They are stored only when the endpoint is created.",
    "Recommandé. BucketReef utilise ces clés pour détecter les capacités RGW Account et Ceph Admin. Elles ne sont enregistrées qu’à la création de l’endpoint.",
    "Empfohlen. BucketReef erkennt damit RGW-Account- und Ceph-Admin-Funktionen. Die Schlüssel werden nur beim Erstellen des Endpunkts gespeichert.",
    "推荐。BucketReef 使用这些密钥检测 RGW Account 和 Ceph Admin 能力，仅在创建端点时保存。",
  ),
  accessKey: l("Access key", "Clé d’accès", "Zugriffsschlüssel", "访问密钥"),
  secretKey: l("Secret key", "Clé secrète", "Geheimer Schlüssel", "密钥密码"),
  keysNotSaved: l(
    "Keys are never stored in onboarding progress.",
    "Les clés ne sont jamais enregistrées dans la progression de l’onboarding.",
    "Schlüssel werden nie im Onboarding-Fortschritt gespeichert.",
    "密钥不会保存在入门进度中。",
  ),
  advanced: l("Advanced connection options", "Options de connexion avancées", "Erweiterte Verbindungsoptionen", "高级连接选项"),
  region: l("Region (optional)", "Région (facultatif)", "Region (optional)", "区域（可选）"),
  addressStyle: l("Addressing style", "Style d’adressage", "Adressierungsstil", "寻址方式"),
  pathStyle: l("Path style", "Path style", "Pfadstil", "路径样式"),
  virtualHost: l("Virtual-hosted style", "Virtual-hosted", "Virtueller Host", "虚拟主机样式"),
  capabilityTitle: l("Detected capabilities", "Capacités détectées", "Erkannte Funktionen", "检测到的能力"),
  detecting: l("Checking the endpoint…", "Vérification de l’endpoint…", "Endpunkt wird geprüft…", "正在检查端点…"),
  detectionHint: l(
    "Capabilities are checked before you choose what to enable.",
    "Les capacités sont vérifiées avant de choisir ce qui doit être activé.",
    "Die Funktionen werden geprüft, bevor Sie auswählen, was aktiviert werden soll.",
    "在选择要启用的功能前会先检查端点能力。",
  ),
  adminOps: l("Admin Ops", "Admin Ops", "Admin Ops", "Admin Ops"),
  accountApi: l("RGW Account API", "API RGW Account", "RGW Account API", "RGW Account API"),
  cephIdentity: l("Ceph Admin identity", "Identité Ceph Admin", "Ceph-Admin-Identität", "Ceph Admin 身份"),
  available: l("Available", "Disponible", "Verfügbar", "可用"),
  unavailable: l("Unavailable", "Indisponible", "Nicht verfügbar", "不可用"),
  continue: l("Continue", "Continuer", "Weiter", "继续"),
  prepareTitle: l("What should BucketReef prepare?", "Que doit préparer BucketReef ?", "Was soll BucketReef vorbereiten?", "BucketReef 应准备什么？"),
  prepareHelp: l(
    "The choices below are limited to what the selected endpoint can support.",
    "Les choix ci-dessous sont limités aux possibilités de l’endpoint sélectionné.",
    "Die Auswahl ist auf die vom Endpunkt unterstützten Möglichkeiten begrenzt.",
    "以下选项仅显示所选端点可支持的能力。",
  ),
  managerTitle: l("Manager with a sample RGW Account", "Manager avec un compte RGW d’exemple", "Manager mit einem RGW-Beispielkonto", "使用示例 RGW Account 的 Manager"),
  managerDesc: l(
    "Create one RGW Account and give your administrator profile account-management and Manager Browser access.",
    "Créer un compte RGW et donner à votre profil administrateur les droits de gestion du compte et d’accès au Browser Manager.",
    "Erstellt ein RGW-Konto und gewährt Ihrem Administratorprofil Kontoverwaltung und Manager-Browser-Zugriff.",
    "创建一个 RGW Account，并授予您的管理员账户管理权限和 Manager Browser 访问权限。",
  ),
  portalTitle: l("Portal with the same sample account", "Portal avec le même compte d’exemple", "Portal mit demselben Beispielkonto", "使用同一示例账户的 Portal"),
  portalDesc: l(
    "Give your profile Portal Manager access and prepare its personal IAM identity. IAM is verified when the configuration is applied.",
    "Donner à votre profil le rôle Portal Manager et préparer son identité IAM personnelle. IAM est vérifié lors de l’application.",
    "Gewährt Portal-Manager-Zugriff und richtet die persönliche IAM-Identität ein. IAM wird beim Anwenden geprüft.",
    "授予 Portal Manager 权限并准备个人 IAM 身份。应用配置时会验证 IAM。",
  ),
  privateTitle: l("Private S3 connection", "Connexion S3 privée", "Private S3-Verbindung", "私有 S3 连接"),
  privateDesc: l(
    "Add a personal connection that can be used directly in Browser and Manager.",
    "Ajouter une connexion personnelle utilisable directement dans Browser et Manager.",
    "Fügt eine persönliche Verbindung für Browser und Manager hinzu.",
    "添加可直接用于 Browser 和 Manager 的个人连接。",
  ),
  cephTitle: l("Ceph Admin", "Ceph Admin", "Ceph Admin", "Ceph Admin"),
  cephDesc: l(
    "Enable the cluster-administration workspace for your administrator profile.",
    "Activer le workspace d’administration du cluster pour votre profil administrateur.",
    "Aktiviert den Cluster-Administrationsbereich für Ihr Administratorprofil.",
    "为您的管理员账户启用集群管理工作区。",
  ),
  recommended: l("Recommended", "Recommandé", "Empfohlen", "推荐"),
  privateCredentials: l("Credentials for your private connection", "Clés de votre connexion privée", "Zugangsdaten für Ihre private Verbindung", "私有连接凭据"),
  privateCredentialsHelp: l(
    "Use the S3 identity you want to browse with. These credentials are separate from the endpoint administration keys.",
    "Utilisez l’identité S3 avec laquelle vous souhaitez parcourir les données. Ces clés sont distinctes des clés d’administration de l’endpoint.",
    "Verwenden Sie die S3-Identität für den Datenzugriff. Diese Zugangsdaten sind von den Endpunkt-Administrationsschlüsseln getrennt.",
    "使用您希望用于浏览数据的 S3 身份。这些凭据与端点管理密钥分开。",
  ),
  summary: l("Changes that will be applied", "Modifications qui seront appliquées", "Anzuwendende Änderungen", "将应用的更改"),
  summaryHelp: l(
    "Review the exact feature activations, resources and access assignments before applying.",
    "Vérifiez les activations, ressources et droits qui seront réellement appliqués.",
    "Prüfen Sie die tatsächlich aktivierten Funktionen, Ressourcen und Zugriffe.",
    "应用前请检查实际将启用的功能、资源和权限。",
  ),
  previewing: l("Updating the summary…", "Actualisation du récapitulatif…", "Übersicht wird aktualisiert…", "正在更新摘要…"),
  noChanges: l("No additional change is required.", "Aucune modification supplémentaire n’est nécessaire.", "Keine zusätzliche Änderung erforderlich.", "无需其他更改。"),
  back: l("Back", "Retour", "Zurück", "返回"),
  apply: l("Apply configuration", "Appliquer la configuration", "Konfiguration anwenden", "应用配置"),
  working: l("Applying configuration…", "Application de la configuration…", "Konfiguration wird angewendet…", "正在应用配置…"),
  dismiss: l("Hide setup", "Masquer l’onboarding", "Einrichtung ausblenden", "隐藏设置"),
  start: l("Start setup", "Commencer", "Einrichtung starten", "开始设置"),
  resume: l("Resume setup", "Reprendre", "Einrichtung fortsetzen", "继续设置"),
  hiddenTitle: l("Setup assistant is hidden", "L’assistant est masqué", "Einrichtungsassistent ist ausgeblendet", "设置向导已隐藏"),
  hiddenDescription: l(
    "You can restore it without changing any storage configuration.",
    "Vous pouvez le réafficher sans modifier la configuration du stockage.",
    "Sie können ihn wieder einblenden, ohne die Speicherkonfiguration zu ändern.",
    "您可以重新显示向导，而不会更改存储配置。",
  ),
  showSetup: l("Show setup assistant", "Réafficher l’assistant", "Einrichtungsassistent anzeigen", "显示设置向导"),
  successTitle: l("BucketReef is ready to explore", "BucketReef est prêt à être exploré", "BucketReef ist bereit", "BucketReef 已准备就绪"),
  successDescription: l(
    "Your selected features and access are configured. You can refine every setting from its workspace at any time.",
    "Les fonctionnalités et accès sélectionnés sont configurés. Vous pouvez affiner chaque réglage depuis son workspace.",
    "Die ausgewählten Funktionen und Zugriffe sind eingerichtet. Details können jederzeit im jeweiligen Arbeitsbereich angepasst werden.",
    "您选择的功能和权限已配置，可随时在相应工作区进一步调整。",
  ),
  openManager: l("Open Manager", "Ouvrir Manager", "Manager öffnen", "打开 Manager"),
  openPortal: l("Open Portal", "Ouvrir Portal", "Portal öffnen", "打开 Portal"),
  openBrowser: l("Open Browser", "Ouvrir Browser", "Browser öffnen", "打开 Browser"),
  openPrivateManager: l("Open private connection in Manager", "Ouvrir la connexion privée dans Manager", "Private Verbindung im Manager öffnen", "在 Manager 中打开私有连接"),
  openCephAdmin: l("Open Ceph Admin", "Ouvrir Ceph Admin", "Ceph Admin öffnen", "打开 Ceph Admin"),
  admin: l("Return to Admin", "Retour à Admin", "Zurück zu Admin", "返回管理界面"),
  retry: l("Retry", "Réessayer", "Erneut versuchen", "重试"),
  signIn: l(
    "Confirm your identity with your passkey to apply this configuration.",
    "Confirmez votre identité avec votre passkey pour appliquer cette configuration.",
    "Bestätigen Sie Ihre Identität mit Ihrem Passkey, um diese Konfiguration anzuwenden.",
    "请使用通行密钥确认身份以应用此配置。",
  ),
};

export const onboardingActions: Record<string, ReturnType<typeof l>> = {
  browser_enabled: l("Enable Browser", "Activer Browser", "Browser aktivieren", "启用 Browser"),
  browser_root_enabled: l("Enable standalone Browser", "Activer Browser autonome", "Eigenständigen Browser aktivieren", "启用独立 Browser"),
  browser_portal_enabled: l("Enable file access in Portal", "Activer l’accès aux fichiers dans Portal", "Dateizugriff im Portal aktivieren", "启用 Portal 文件访问"),
  manager_enabled: l("Enable Manager", "Activer Manager", "Manager aktivieren", "启用 Manager"),
  portal_enabled: l("Enable Portal", "Activer Portal", "Portal aktivieren", "启用 Portal"),
  ceph_admin_enabled: l("Enable Ceph Admin", "Activer Ceph Admin", "Ceph Admin aktivieren", "启用 Ceph Admin"),
  create_ceph_endpoint: l("Create the Ceph RGW endpoint", "Créer l’endpoint Ceph RGW", "Ceph-RGW-Endpunkt erstellen", "创建 Ceph RGW 端点"),
  validate_ceph_account_api: l("Validate Admin Ops and RGW Account API", "Valider Admin Ops et l’API RGW Account", "Admin Ops und RGW Account API prüfen", "验证 Admin Ops 和 RGW Account API"),
  enable_endpoint_account_features: l("Enable the endpoint’s Admin Ops and Account capabilities", "Activer les capacités Admin Ops et Account de l’endpoint", "Admin-Ops- und Account-Funktionen des Endpunkts aktivieren", "启用端点 Admin Ops 和 Account 能力"),
  validate_portal_iam: l("Validate and enable IAM for Portal", "Valider et activer IAM pour Portal", "IAM für Portal prüfen und aktivieren", "验证并为 Portal 启用 IAM"),
  validate_ceph_admin: l("Validate the Ceph Admin identity", "Valider l’identité Ceph Admin", "Ceph-Admin-Identität prüfen", "验证 Ceph Admin 身份"),
  create_sample_account: l("Create one sample RGW Account", "Créer un compte RGW d’exemple", "Ein RGW-Beispielkonto erstellen", "创建一个示例 RGW Account"),
  resume_sample_account: l("Resume the same sample RGW Account provisioning", "Reprendre le provisionnement du même compte RGW d’exemple", "Bereitstellung desselben RGW-Beispielkontos fortsetzen", "继续配置同一个示例 RGW Account"),
  grant_manager_access: l("Give your profile Account Administrator and Manager Browser access", "Donner à votre profil les droits Account Administrator et Browser Manager", "Account-Administrator- und Manager-Browser-Zugriff gewähren", "授予 Account Administrator 和 Manager Browser 权限"),
  grant_portal_access: l("Give your profile Portal Manager access", "Donner à votre profil le rôle Portal Manager", "Portal-Manager-Zugriff gewähren", "授予 Portal Manager 权限"),
  prepare_portal_identity: l("Prepare your personal Portal IAM identity", "Préparer votre identité IAM personnelle Portal", "Persönliche Portal-IAM-Identität vorbereiten", "准备个人 Portal IAM 身份"),
  create_private_connection: l("Create your private Browser + Manager connection", "Créer votre connexion privée Browser + Manager", "Private Browser- und Manager-Verbindung erstellen", "创建私有 Browser + Manager 连接"),
  allow_private_connections: l("Allow your profile to create private connections", "Autoriser votre profil à créer des connexions privées", "Erstellen privater Verbindungen erlauben", "允许您的账户创建私有连接"),
  grant_ceph_admin_access: l("Allow your profile to use Ceph Admin", "Autoriser votre profil à utiliser Ceph Admin", "Ceph-Admin-Zugriff gewähren", "允许您的账户使用 Ceph Admin"),
};

export const onboardingErrors: Record<string, ReturnType<typeof l>> = {
  selection_required: l("Choose at least one feature to prepare.", "Choisissez au moins une fonctionnalité à préparer.", "Wählen Sie mindestens eine Funktion aus.", "请至少选择一个要准备的功能。"),
  endpoint_required: l("Choose an existing endpoint or enter a new endpoint URL.", "Choisissez un endpoint existant ou saisissez une nouvelle URL.", "Wählen Sie einen vorhandenen Endpunkt oder geben Sie eine neue URL ein.", "请选择已有端点或输入新的端点 URL。"),
  endpoint_unavailable: l("The selected endpoint is no longer available.", "L’endpoint sélectionné n’est plus disponible.", "Der ausgewählte Endpunkt ist nicht mehr verfügbar.", "所选端点已不可用。"),
  endpoints_locked: l("Endpoints are managed by the deployment environment. Select an existing endpoint.", "Les endpoints sont gérés par l’environnement de déploiement. Sélectionnez un endpoint existant.", "Endpunkte werden durch die Umgebung verwaltet. Wählen Sie einen vorhandenen Endpunkt.", "端点由部署环境管理，请选择已有端点。"),
  ceph_endpoint_required: l("This option requires a Ceph RGW endpoint.", "Cette option nécessite un endpoint Ceph RGW.", "Diese Option benötigt einen Ceph-RGW-Endpunkt.", "此选项需要 Ceph RGW 端点。"),
  endpoint_admin_credentials_required: l("Manager and Portal require valid Ceph Admin Ops credentials on this endpoint.", "Manager et Portal nécessitent des clés Ceph Admin Ops valides sur cet endpoint.", "Manager und Portal benötigen gültige Ceph Admin Ops-Zugangsdaten.", "Manager 和 Portal 需要此端点上的有效 Ceph Admin Ops 凭据。"),
  ceph_admin_credentials_required: l("Ceph Admin requires configured admin/system credentials on this endpoint.", "Ceph Admin nécessite des clés admin/system configurées sur cet endpoint.", "Ceph Admin benötigt konfigurierte Admin/System-Zugangsdaten.", "Ceph Admin 需要此端点上已配置的 admin/system 凭据。"),
  endpoint_features_locked: l("A required endpoint capability is disabled and the endpoint is managed by the deployment environment.", "Une capacité requise est désactivée et l’endpoint est géré par l’environnement de déploiement.", "Eine benötigte Endpunktfunktion ist deaktiviert und durch die Umgebung verwaltet.", "所需端点能力已禁用且由部署环境管理。"),
  account_api_unavailable: l("The endpoint did not validate Admin Ops and RGW Account provisioning.", "L’endpoint n’a pas validé Admin Ops et le provisionnement RGW Account.", "Der Endpunkt hat Admin Ops und RGW Account nicht bestätigt.", "端点未验证 Admin Ops 和 RGW Account 配置能力。"),
  ceph_identity_denied: l("Ceph Admin requires an RGW identity created with admin or system privileges.", "Ceph Admin nécessite une identité RGW créée avec les privilèges admin ou system.", "Ceph Admin benötigt eine RGW-Identität mit Admin- oder Systemrechten.", "Ceph Admin 需要具有 admin 或 system 权限的 RGW 身份。"),
  endpoint_credentials_invalid: l("The endpoint administration credentials could not be validated.", "Les clés d’administration de l’endpoint n’ont pas pu être validées.", "Die Administrationszugangsdaten konnten nicht bestätigt werden.", "无法验证端点管理凭据。"),
  private_credentials_required: l("Enter the access key and secret key for the private connection.", "Renseignez la clé d’accès et la clé secrète de la connexion privée.", "Geben Sie Zugriffsschlüssel und geheimen Schlüssel für die private Verbindung ein.", "请输入私有连接的访问密钥和密钥密码。"),
  credentials_required: l("Enter both the access key and secret key.", "Renseignez la clé d’accès et la clé secrète.", "Geben Sie Zugriffsschlüssel und geheimen Schlüssel ein.", "请输入访问密钥和密钥密码。"),
  review_changed: l("The configuration changed since the summary was displayed. Review it again.", "La configuration a changé depuis l’affichage du récapitulatif. Vérifiez-le à nouveau.", "Die Konfiguration hat sich seit der Übersicht geändert. Prüfen Sie sie erneut.", "配置自摘要显示后已发生变化，请重新检查。"),
  stale_revision: l("This setup changed in another tab. Reload it before continuing.", "Cette configuration a changé dans un autre onglet. Rechargez-la avant de continuer.", "Diese Einrichtung wurde in einem anderen Tab geändert. Laden Sie sie neu.", "此设置已在另一个标签页中更改，请重新加载。"),
  configured_journey_immutable: l("This setup is already complete. Start the assistant again to prepare another configuration.", "Cette configuration est déjà terminée. Relancez l’assistant pour préparer une autre configuration.", "Diese Einrichtung ist abgeschlossen. Starten Sie den Assistenten erneut.", "此设置已完成，请重新启动向导以准备其他配置。"),
  configuration_reconciliation_required: l("A storage resource was already created. Retry the saved configuration before changing the selection.", "Une ressource de stockage a déjà été créée. Réessayez la configuration enregistrée avant de modifier la sélection.", "Eine Speicherressource wurde bereits erstellt. Wiederholen Sie die gespeicherte Einrichtung, bevor Sie die Auswahl ändern.", "已创建存储资源，请先重试保存的配置，再更改选择。"),
  configuration_busy: l("A setup request is already running for your profile.", "Une configuration est déjà en cours pour votre profil.", "Für Ihr Profil läuft bereits eine Einrichtung.", "您的账户已有设置请求正在执行。"),
  invalid_configuration: l("Check the endpoint and selected options.", "Vérifiez l’endpoint et les options sélectionnées.", "Prüfen Sie Endpunkt und Auswahl.", "请检查端点和所选选项。"),
  storage_access_denied: l("Storage denied the operation. Check the selected credentials.", "Le stockage refuse l’opération. Vérifiez les clés utilisées.", "Der Speicher hat die Aktion verweigert. Prüfen Sie die Zugangsdaten.", "存储拒绝了该操作，请检查所用凭据。"),
  storage_unavailable: l("The storage service could not complete the request. Check endpoint connectivity.", "Le service de stockage n’a pas pu traiter la requête. Vérifiez la connectivité de l’endpoint.", "Der Speicherdienst konnte die Anfrage nicht abschließen. Prüfen Sie die Verbindung.", "存储服务无法完成请求，请检查端点连接。"),
  superadmin_required: l("A platform superadministrator is required to apply setup changes.", "Un superadministrateur de la plateforme est nécessaire pour appliquer la configuration.", "Zum Anwenden ist ein Plattform-Superadministrator erforderlich.", "应用设置更改需要平台超级管理员权限。"),
  env_locked: l("This feature is disabled by the deployment environment", "Cette fonctionnalité est désactivée par l’environnement de déploiement", "Diese Funktion ist durch die Bereitstellungsumgebung deaktiviert", "此功能已被部署环境禁用"),
  generic: l("Setup could not complete. The saved progress can be retried safely.", "La configuration n’a pas abouti. La progression enregistrée peut être reprise sans créer de doublon.", "Die Einrichtung konnte nicht abgeschlossen werden. Der gespeicherte Stand kann sicher erneut ausgeführt werden.", "设置未完成，可安全重试已保存的进度。"),
};
