import type { AppSettings } from "../../../api/appSettings";
export function createAppSettings(
  overrides: Partial<AppSettings["general"]> = {},
): AppSettings {
  return {
    general: {
      managed_private_connection_provisioning_enabled: false,
      require_passkey_for_admins: true,
      require_passkey_for_users: false,
      allow_user_profile_name_edit: false,
      allow_user_external_identity_unlink: false,
      manager_enabled: true,
      ceph_admin_enabled: false,
      storage_ops_enabled: false,
      browser_enabled: true,
      browser_root_enabled: true,
      browser_manager_enabled: true,
      browser_portal_enabled: true,
      browser_ceph_admin_enabled: false,
      portal_enabled: true,
      billing_enabled: false,
      endpoint_status_enabled: false,
      quota_alerts_enabled: false,
      usage_history_enabled: false,
      bucket_migration_enabled: true,
      bucket_purge_enabled: false,
      bucket_compare_enabled: true,
      bucket_integrity_check_enabled: true,
      bucket_usage_stats_enabled: true,
      bucket_quota_management_enabled: true,
      manager_ceph_s3_user_keys_enabled: true,
      allow_login_access_keys: false,
      allow_login_endpoint_list: false,
      allow_login_custom_endpoint: false,
      ...overrides,
    },
    portal: {
      browser_access_enabled: false,
      allow_private_storage_space_create: true,
      allow_portal_named_bucket_create: false,
      allow_portal_user_access_key_create: true,
      allow_portal_user_external_sharing: false,
      server_access_logging_enabled: true,
      server_access_log_retention_days: 30,
      storage_space_version_cleanup_enabled: true,
      max_portal_user_access_keys: 2,
      bucket_defaults: {
        versioning: false,
        enable_cors: true,
        enable_lifecycle: false,
        noncurrent_version_expiration_days: 90,
        cors_allowed_origins: [],
      },
    },
    manager: {
      manager_rgw_usage_metrics_enabled: true,
      bucket_migration_parallelism_default: 8,
      bucket_migration_parallelism_max: 16,
      bucket_migration_max_active_per_endpoint: 2,
    },
    quota_notifications: {
      threshold_percent: 85,
      include_subject_contact_email: false,
      smtp_host: null,
      smtp_port: 587,
      smtp_username: null,
      smtp_from_email: null,
      smtp_from_name: null,
      smtp_starttls: true,
      smtp_timeout_seconds: 15,
    },
    browser: {
      allow_proxy_transfers: true,
      direct_upload_parallelism: 5,
      proxy_upload_parallelism: 2,
      direct_download_parallelism: 5,
      proxy_download_parallelism: 2,
      other_operations_parallelism: 3,
      streaming_zip_threshold_mb: 200,
    },
    onboarding: { dismissed: false },
    branding: {
      primary_color: "#0569f8",
      login_logo_url: null,
    },
  };
}
