services:
  backend:
    environment:
      FEATURE_ADMIN_ENABLED: "true"
      FEATURE_CEPH_ADMIN_ENABLED: "true"
      FEATURE_STORAGE_OPS_ENABLED: "true"
      FEATURE_MANAGER_ENABLED: "false"
      FEATURE_PORTAL_ENABLED: "false"
      FEATURE_BROWSER_ENABLED: "false"
      SCHEDULED_JOBS_ENABLED: "true"
