#!/usr/bin/env python3
"""Deterministic historical release metadata and offline documentation."""
from __future__ import annotations
import argparse
from datetime import date
import json
from pathlib import Path
import re
import subprocess
from release_notes import ROOT, changelog_section, previous_tag, render_notes, version_tuple

GITHUB = 'https://github.com/ksperis/bucketreef'
GITLAB = 'https://gitlab.ksperis.com/laurent/bucketreef'


def git(root, *args):
    return subprocess.check_output(['git', *args], cwd=root, text=True, stderr=subprocess.DEVNULL).strip()


def load_catalog(path, root=ROOT):
    catalog = json.loads(Path(path).read_text())
    if catalog.get('schema') != 1:
        raise ValueError('Unsupported history catalog schema')
    version_tuple(catalog['latest'])
    seen = set()
    for entry in catalog['releases']:
        version = entry['version']
        version_tuple(version)
        if version in seen or version_tuple(version) > version_tuple(catalog['latest']):
            raise ValueError('Duplicate or newer-than-latest catalog version')
        seen.add(version)
        if not re.fullmatch(r'[0-9a-f]{40}', entry['sha']):
            raise ValueError('Expected full commit SHA')
        if git(root, 'rev-parse', f'v{version}^{{commit}}') != entry['sha']:
            raise ValueError(f'Local tag differs from catalog: {version}')
        date.fromisoformat(entry['date'])
        if entry['date_source'] not in {'changelog', 'tag', 'commit'}:
            raise ValueError('Invalid date provenance')
        if not isinstance(entry['confirmed'], bool) or not isinstance(entry['reconstructed'], bool):
            raise ValueError('Invalid publication flags')
        if entry.get('previous_gitlab_sha') and not re.fullmatch(r'[0-9a-f]{40}', entry['previous_gitlab_sha']):
            raise ValueError('Invalid historical tag reference')
        changelog_section((root / 'CHANGELOG.md').read_text(), version)
    if catalog['latest'] not in seen:
        raise ValueError('Latest release is absent from catalog')
    return catalog


def section(entry, root=ROOT):
    text = changelog_section((root / 'CHANGELOG.md').read_text(), entry['version'])
    if entry.get('previous_gitlab_sha'):
        text += ('\n### Historical tag alignment\n\n'
                 f"The GitLab tag was aligned with GitHub at `{entry['sha']}` "
                 f"from `{entry['previous_gitlab_sha']}`. Existing container images were not rebuilt "
                 'or republished; this tag alignment does not establish their provenance.\n')
    return text


def notes(entry, platform, root=ROOT):
    previous = previous_tag(root, entry['version'], entry['sha'])
    base = GITLAB if platform == 'gitlab' else GITHUB
    text = render_notes(section(entry, root), entry['version'], previous, base, gitlab=platform == 'gitlab')
    if previous is None:
        text += f"\n**Source:** [v{entry['version']}]({base}/{'-/tree' if platform == 'gitlab' else 'tree'}/v{entry['version']})\n"
    return text


def documentation(catalog, root=ROOT):
    entries = sorted((e for e in catalog['releases'] if e['confirmed']), key=lambda e: version_tuple(e['version']), reverse=True)
    lines = ['# Releases', '', '<!-- Generated by ops/release/history.py; edit CHANGELOG.md and the confirmed catalog. -->', '',
             'Release notes and links for confirmed GitHub and GitLab publications. Historical notes may be incomplete.', '',
             'Dates come from the changelog where available, otherwise from the annotated tag or tagged commit. They are not retrospective GitHub publication timestamps.', '',
             '| Version | Date | Notes | Publications |', '| --- | --- | --- | --- |']
    for e in entries:
        v=e['version']; label='Reconstructed' if e['reconstructed'] else 'Changelog'
        lines.append(f"| [{v}](#release-{v.replace('.', '-')}) | {e['date']} ({e['date_source']}) | {label} | [GitHub]({GITHUB}/releases/tag/v{v}) · [GitLab]({GITLAB}/-/releases/v{v}) |")
    for e in entries:
        v=e['version']
        lines += ['', f"## {v} {{#release-{v.replace('.', '-')}}}", '',
                  f"[GitHub release]({GITHUB}/releases/tag/v{v}) · [GitLab release]({GITLAB}/-/releases/v{v})", '']
        previous=previous_tag(root,v,e['sha'])
        if previous:
            lines += [f"Compare {previous} → v{v}: [GitHub]({GITHUB}/compare/{previous}...v{v}) · [GitLab]({GITLAB}/-/compare/{previous}...v{v})", '']
        lines += section(e,root).splitlines()[1:]
    return '\n'.join(lines).rstrip()+'\n'


if __name__ == '__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--catalog',type=Path,default=ROOT/'ops/release/history.json')
    parser.add_argument('--output',type=Path,default=ROOT/'doc/docs/releases.md')
    parser.add_argument('--check',action='store_true')
    args=parser.parse_args()
    text=documentation(load_catalog(args.catalog))
    if args.check:
        if not args.output.exists() or args.output.read_text()!=text:
            raise SystemExit('Release documentation is stale; regenerate it with ops/release/history.py')
    else:
        args.output.write_text(text)
