#!/usr/bin/env python3
"""Deterministic historical release metadata and offline documentation."""
from __future__ import annotations
import argparse
from datetime import date
import json
from pathlib import Path
import re
import subprocess
from release_notes import ROOT, VERSION_PATTERN, changelog_section, previous_tag, render_notes, version_tuple

GITHUB = 'https://github.com/ksperis/bucketreef'
GITLAB = 'https://gitlab.ksperis.com/laurent/bucketreef'


def git(root, *args):
    return subprocess.check_output(['git', *args], cwd=root, text=True, stderr=subprocess.DEVNULL).strip()


def load_catalog(path, root=ROOT):
    catalog = json.loads(Path(path).read_text())
    if catalog.get('schema') != 1:
        raise ValueError('Unsupported history catalog schema')
    version_tuple(catalog['latest'])
    seen = set()
    for entry in catalog['releases']:
        version = entry['version']
        version_tuple(version)
        if version in seen or version_tuple(version) > version_tuple(catalog['latest']):
            raise ValueError('Duplicate or newer-than-latest catalog version')
        seen.add(version)
        if not re.fullmatch(r'[0-9a-f]{40}', entry['sha']):
            raise ValueError('Expected full commit SHA')
        if git(root, 'rev-parse', f'v{version}^{{commit}}') != entry['sha']:
            raise ValueError(f'Local tag differs from catalog: {version}')
        date.fromisoformat(entry['date'])
        if entry['date_source'] not in {'changelog', 'tag', 'commit'}:
            raise ValueError('Invalid date provenance')
        if not isinstance(entry['confirmed'], bool) or not isinstance(entry['reconstructed'], bool):
            raise ValueError('Invalid publication flags')
        if entry.get('previous_gitlab_sha') and not re.fullmatch(r'[0-9a-f]{40}', entry['previous_gitlab_sha']):
            raise ValueError('Invalid historical tag reference')
        changelog_section((root / 'CHANGELOG.md').read_text(), version)
    if catalog['latest'] not in seen:
        raise ValueError('Latest release is absent from catalog')
    return catalog


def section(entry, root=ROOT):
    text = changelog_section((root / 'CHANGELOG.md').read_text(), entry['version'])
    if entry.get('previous_gitlab_sha'):
        text += ('\n### Historical tag alignment\n\n'
                 f"The GitLab tag was aligned with GitHub at `{entry['sha']}` "
                 f"from `{entry['previous_gitlab_sha']}`. Existing container images were not rebuilt "
                 'or republished; this tag alignment does not establish their provenance.\n')
    return text


def notes(entry, platform, root=ROOT):
    previous = previous_tag(root, entry['version'], entry['sha'])
    base = GITLAB if platform == 'gitlab' else GITHUB
    text = render_notes(section(entry, root), entry['version'], previous, base, gitlab=platform == 'gitlab')
    if previous is None:
        text += f"\n**Source:** [v{entry['version']}]({base}/{'-/tree' if platform == 'gitlab' else 'tree'}/v{entry['version']})\n"
    return text


def changelog_releases(root=ROOT):
    text = (root / 'CHANGELOG.md').read_text()
    entries = []
    seen = set()
    pattern = re.compile(rf'^## \[?({VERSION_PATTERN})\]?(?: - (\d{{4}}-\d{{2}}-\d{{2}}))?$', re.MULTILINE)
    for match in pattern.finditer(text):
        version, release_date = match.groups()
        if version in seen:
            raise ValueError(f'Duplicate changelog release: {version}')
        seen.add(version)
        changelog_section(text, version)
        if release_date:
            date.fromisoformat(release_date)
        entries.append({'version': version, 'date': release_date})
    if not entries:
        raise ValueError('CHANGELOG.md does not contain any stable release')
    return entries


def documentation_catalog(root=ROOT):
    path = root / 'ops/release/history.json'
    if not path.exists():
        return {'schema': 1, 'latest': None, 'releases': []}
    return load_catalog(path, root)


def documentation(catalog, root=ROOT):
    catalog_entries = {entry['version']: entry for entry in catalog['releases']}
    entries = []
    for changelog_entry in changelog_releases(root):
        version = changelog_entry['version']
        historical = catalog_entries.get(version)
        if historical:
            entry = dict(historical)
        else:
            if not changelog_entry['date']:
                raise ValueError(f'Changelog release {version} requires a date or historical catalog metadata')
            entry = {
                'version': version,
                'date': changelog_entry['date'],
                'date_source': 'changelog',
                'reconstructed': False,
            }
        entries.append(entry)
    entries.sort(key=lambda e: version_tuple(e['version']), reverse=True)
    versions = [entry['version'] for entry in entries]
    lines = ['# Releases', '', '<!-- Generated by ops/release/history.py; edit CHANGELOG.md and historical metadata in ops/release/history.json. -->', '',
             'Release notes are generated from `CHANGELOG.md`; publication links point to the corresponding GitHub release. Historical notes may be incomplete.', '',
             'Current release dates come from the changelog; reconstructed historical dates retain their catalog provenance from the changelog, annotated tag, or tagged commit. They are not retrospective GitHub publication timestamps.', '',
             '| Version | Date | Notes | Publications |', '| --- | --- | --- | --- |']
    for e in entries:
        v=e['version']; label='Reconstructed' if e['reconstructed'] else 'Changelog'
        lines.append(f"| [{v}](#release-{v.replace('.', '-')}) | {e['date']} ({e['date_source']}) | {label} | [GitHub]({GITHUB}/releases/tag/v{v}) |")
    for e in entries:
        v=e['version']
        lines += ['', f"## {v} {{#release-{v.replace('.', '-')}}}", '',
                  f"[GitHub release]({GITHUB}/releases/tag/v{v})", '']
        previous_versions = [candidate for candidate in versions if version_tuple(candidate) < version_tuple(v)]
        previous = f"v{max(previous_versions, key=version_tuple)}" if previous_versions else None
        if previous:
            lines += [f"Compare {previous} → v{v}: [GitHub]({GITHUB}/compare/{previous}...v{v})", '']
        lines += section(e,root).splitlines()[1:]
    return '\n'.join(lines).rstrip()+'\n'


def documentation_for_root(root=ROOT):
    return documentation(documentation_catalog(root), root)


def write_documentation(root=ROOT, output=None):
    output = output or root / 'doc/docs/releases.md'
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(documentation_for_root(root))


if __name__ == '__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--catalog',type=Path,default=ROOT/'ops/release/history.json')
    parser.add_argument('--output',type=Path,default=ROOT/'doc/docs/releases.md')
    parser.add_argument('--check',action='store_true')
    args=parser.parse_args()
    text=documentation(load_catalog(args.catalog))
    if args.check:
        if not args.output.exists() or args.output.read_text()!=text:
            raise SystemExit('Release documentation is stale; regenerate it with ops/release/history.py')
    else:
        args.output.write_text(text)
